{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.juloass.tofuxia-engine",
    "module": "engine-ui",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "engine-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "localization-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "math",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "ui-animation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "engine-ui-0.1.0.jar",
          "url": "engine-ui-0.1.0.jar",
          "size": 101387,
          "sha512": "b96f35f176197e6296d69794a76295ce25c4bfd05b8c2041e222ecf046a33e1928e0feb65fe1ef52cb785d79e845e2c231f783b49ef302175be72955ae26c524",
          "sha256": "d8157e0bfb84771a1a5ecd262fde7cbcdf3fcdc789064e79af8750921fc3d495",
          "sha1": "ba3a46d5fc7ac98078f6de463dd2652846669eaf",
          "md5": "95f1c074716d9a7b73dfd19984732b06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "engine-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "localization-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "math",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "ui-animation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "engine-ui-0.1.0.jar",
          "url": "engine-ui-0.1.0.jar",
          "size": 101387,
          "sha512": "b96f35f176197e6296d69794a76295ce25c4bfd05b8c2041e222ecf046a33e1928e0feb65fe1ef52cb785d79e845e2c231f783b49ef302175be72955ae26c524",
          "sha256": "d8157e0bfb84771a1a5ecd262fde7cbcdf3fcdc789064e79af8750921fc3d495",
          "sha1": "ba3a46d5fc7ac98078f6de463dd2652846669eaf",
          "md5": "95f1c074716d9a7b73dfd19984732b06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "engine-ui-0.1.0-sources.jar",
          "url": "engine-ui-0.1.0-sources.jar",
          "size": 40260,
          "sha512": "19710b867567e9309ec09ad661a925e37c734d02af2480a74d45ff7a419d44e28578ef5802d88086ac8ae2b44a666031b5579c60e44192d62d37b637750c5c36",
          "sha256": "96e284b7217bdea18a2fddb0e602158891779f99e7a9a12090295e10facd0b00",
          "sha1": "6ccdbeca076a741ac325803fa616d4b9e050bc72",
          "md5": "edee21dbfa25cf07e224d5ea5036f8ff"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "engine-ui-0.1.0-javadoc.jar",
          "url": "engine-ui-0.1.0-javadoc.jar",
          "size": 277490,
          "sha512": "cccaf5e29823ca683d9578890c986a60f456e3b967d182a47afbacdc91529d76af61b78fd15a9c799ed628d3034340b2b648fa21d76e9d18a9ee477082f67b0b",
          "sha256": "1696368d699ba9f3cc89733862a81b32fd81a1ae0eeca1d1f639299c034b0ee5",
          "sha1": "970c1f20150c3877842d7c898efdd4035c6c6549",
          "md5": "cbeb31a965224c60586c0f6adbfb99d0"
        }
      ]
    }
  ]
}
