{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.juloass.tofuxia-engine",
    "module": "engine-app",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "engine-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "engine-ui",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "localization-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "audio-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "input-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "particle-engine",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "vulkan-renderer",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "engine-app-0.1.0.jar",
          "url": "engine-app-0.1.0.jar",
          "size": 224734,
          "sha512": "6a41b99ad6272c1a9e3e4f6adf639794806fd7df3aa84df08dd7efab24954d2b9405879189973aae1abdcb8f1a08ec54733801133331b19991b7736203fa640a",
          "sha256": "cf87b0f912c6c63b3fff2cfe0aec275c03484be32f620272a70c49c5a8ca3d28",
          "sha1": "348a7ad20f2facebc60244e4e30f6b4710069bf8",
          "md5": "cf4da0d8b125d6a1aa4df5111bf1b6f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.9"
          }
        },
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "engine-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "engine-ui",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "localization-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "audio-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "input-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "particle-engine",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "vulkan-renderer",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "engine-app-0.1.0.jar",
          "url": "engine-app-0.1.0.jar",
          "size": 224734,
          "sha512": "6a41b99ad6272c1a9e3e4f6adf639794806fd7df3aa84df08dd7efab24954d2b9405879189973aae1abdcb8f1a08ec54733801133331b19991b7736203fa640a",
          "sha256": "cf87b0f912c6c63b3fff2cfe0aec275c03484be32f620272a70c49c5a8ca3d28",
          "sha1": "348a7ad20f2facebc60244e4e30f6b4710069bf8",
          "md5": "cf4da0d8b125d6a1aa4df5111bf1b6f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "engine-app-0.1.0-sources.jar",
          "url": "engine-app-0.1.0-sources.jar",
          "size": 58412,
          "sha512": "900148baa90a2da002885582e7ffa03f6dee9a17b84fcccb753df993e194fb6ea7a8b2df09266a6a821875d5bde610f08b05ab6cef1aa406fe3881722bd8c427",
          "sha256": "5b32bf8e187cc9559f8ea6d5bda7135275611c941af978c8c5cabe676e0208c2",
          "sha1": "1e2add5936d7422415498b17a567ebb67126197c",
          "md5": "9e6065c83d225cab62fc47e8f544defa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "engine-app-0.1.0-javadoc.jar",
          "url": "engine-app-0.1.0-javadoc.jar",
          "size": 540502,
          "sha512": "4238c7218a5f8c470d3602efd8a16f753a33a17031b2a91533e51895bc2dff0eb8548873991c51fe56e5a3c4aa1a859281a7469be3b3e4565855e892612f3db3",
          "sha256": "152515bf4615ab448c814292f11ee96acc173ac450e1e88f573c803bcdda75ef",
          "sha1": "7d8e09823a0faf11176abe7212f625a83c33ac91",
          "md5": "fbd1a5c750761321349cedbb10e8ad68"
        }
      ]
    }
  ]
}
