{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.juloass",
    "module": "color",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "color-1.0.1.jar",
          "url": "color-1.0.1.jar",
          "size": 45789,
          "sha512": "1831d0c7ed6f60db97117473d67dba163b56f69eb243bb7e107523ff0575dcbbe2e4b53abf3a0c35bb87be8ca7d43966ce4225bce023a43227d2a93437cc233c",
          "sha256": "73ea62ff9083742db0321a75ad467cc10ba6b461c8b164b63b7212dcba3802a9",
          "sha1": "f58a0c88ff0b747b230ab169253cc9bdff96fcec",
          "md5": "c24df97e45270e3d61b6e83bd3295832"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.juloass",
          "module": "math",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "color-1.0.1.jar",
          "url": "color-1.0.1.jar",
          "size": 45789,
          "sha512": "1831d0c7ed6f60db97117473d67dba163b56f69eb243bb7e107523ff0575dcbbe2e4b53abf3a0c35bb87be8ca7d43966ce4225bce023a43227d2a93437cc233c",
          "sha256": "73ea62ff9083742db0321a75ad467cc10ba6b461c8b164b63b7212dcba3802a9",
          "sha1": "f58a0c88ff0b747b230ab169253cc9bdff96fcec",
          "md5": "c24df97e45270e3d61b6e83bd3295832"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "color-1.0.1-sources.jar",
          "url": "color-1.0.1-sources.jar",
          "size": 13071,
          "sha512": "7c9218a61abdcc06b5caadb7668f9e6519e2d3327da86b26cc77a11314636d5413b2d54c24d45d13bca2ace8625af396c9e130bfb2b1d7eda779b6ff9bffb066",
          "sha256": "0945f7a0b47dbfc130ac1488759b49f63adadfc2292f84c2a892555371c0ea68",
          "sha1": "10bf26534cb777d49fff5a1c10bac37e6b624af4",
          "md5": "de21d768c941e8579cd9efb351f3fd69"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "color-1.0.1-javadoc.jar",
          "url": "color-1.0.1-javadoc.jar",
          "size": 165919,
          "sha512": "1b568b524a6a58ce7877bfb48169fa9cfa3a5cbbd902af6af868c904c651bab7c41ede48b12a54b098f19411181233bbcd3e4e8049c9eed3797f6833204570d4",
          "sha256": "6be8f7c1f029cd42d1f5de6618db00566bfdf0d3fa4a2eb93b32a3fbce9a6612",
          "sha1": "6e7e7d155828b8c1908121e7217b1abef29ce9ec",
          "md5": "8f771195e7d0d42df2a3163c6d910be2"
        }
      ]
    }
  ]
}
