{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.juloass.tofuxia-engine",
    "module": "engine-desktop",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "engine-app",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "engine-desktop-0.2.0.jar",
          "url": "engine-desktop-0.2.0.jar",
          "size": 46961,
          "sha512": "9fa853c81f13709b61817f40557f3966d89461a922476a48b6b70f3ea619f1178a31d3e5a44b7f64d9a67c138c6ccd3c3064424265325f94c3bde3699cc96734",
          "sha256": "12f6ea7a6db704835bfed8b4ac3e520664650817a240a13264f26d467a8cc313",
          "sha1": "e2554f33ff3345d0d39cafba107309a5a749002c",
          "md5": "074ee932a14f6571aa0f6b13db4cd4cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "vulkan-renderer",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "localization-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "localization-resource",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "audio-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "audio-openal",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "audio-resource",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "input-glfw",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.0.18"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-bom",
          "version": {
            "requires": "3.4.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "engine-app",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "engine-desktop-0.2.0.jar",
          "url": "engine-desktop-0.2.0.jar",
          "size": 46961,
          "sha512": "9fa853c81f13709b61817f40557f3966d89461a922476a48b6b70f3ea619f1178a31d3e5a44b7f64d9a67c138c6ccd3c3064424265325f94c3bde3699cc96734",
          "sha256": "12f6ea7a6db704835bfed8b4ac3e520664650817a240a13264f26d467a8cc313",
          "sha1": "e2554f33ff3345d0d39cafba107309a5a749002c",
          "md5": "074ee932a14f6571aa0f6b13db4cd4cd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "engine-desktop-0.2.0-sources.jar",
          "url": "engine-desktop-0.2.0-sources.jar",
          "size": 18770,
          "sha512": "f56090299597e7b3e3e5ee0aa485bc1c0c692eb52c5ca837797fe88b3dae04b15bc25b7110839d9b3bcb84649a2fb7daf98e2645d7bd00133ff5ca06a61c2301",
          "sha256": "26976ae185244b0762b6efd6054999c3b6b728a65a1cd16d2b554ddab5832539",
          "sha1": "05de6c3b247e812168c87d41656d43d833532ab5",
          "md5": "539d4afc52b0ad218f680088d062f988"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "engine-desktop-0.2.0-javadoc.jar",
          "url": "engine-desktop-0.2.0-javadoc.jar",
          "size": 86077,
          "sha512": "3ee63a9c2b0a494eea78e22132e9fe92345b16c8c1381e4bcad4b43e37bccc23ecb48ba2304d9ccf197597f94506340fc05c97bb9ecbba87c5d4341442940426",
          "sha256": "6b23801d6dd56d64f153cf520b418e716b9afc4b37d4a346957d41a08b6c4d02",
          "sha1": "fc167d47873e8d1a39e1c00e692e8898c29da733",
          "md5": "274486dd1effb2639569f7e141a44aac"
        }
      ]
    }
  ]
}
