{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.juloass",
    "module": "localization-core",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.juloass",
          "module": "color",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "localization-core-0.1.0.jar",
          "url": "localization-core-0.1.0.jar",
          "size": 51708,
          "sha512": "7a1933115bef803b612a54e6a2489b0799985a75c02949b583a8c09a002fd0b631eb083df9f0a5712289460f45bc33de3bb49f117ae43d12d0aa336c7c6d2aa8",
          "sha256": "e4394a076b695f397eb0c7662554553efba46394a4d2e0203a18bb96a6e8cfb0",
          "sha1": "a1235d916dc58baae2769652eab23d3f247c73f4",
          "md5": "c1094a8f3be8bcb7adea8bf6ee2377ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.juloass",
          "module": "color",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "localization-core-0.1.0.jar",
          "url": "localization-core-0.1.0.jar",
          "size": 51708,
          "sha512": "7a1933115bef803b612a54e6a2489b0799985a75c02949b583a8c09a002fd0b631eb083df9f0a5712289460f45bc33de3bb49f117ae43d12d0aa336c7c6d2aa8",
          "sha256": "e4394a076b695f397eb0c7662554553efba46394a4d2e0203a18bb96a6e8cfb0",
          "sha1": "a1235d916dc58baae2769652eab23d3f247c73f4",
          "md5": "c1094a8f3be8bcb7adea8bf6ee2377ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "localization-core-0.1.0-sources.jar",
          "url": "localization-core-0.1.0-sources.jar",
          "size": 16705,
          "sha512": "48ba0f439f4257212ab0e824665a521916f6cc95d8ab8c422b899879fcccbbc6f346c8bda2754706205d17f69d17caf2ecd65401f4c2f1aa99c662c87242b988",
          "sha256": "cfe977ff66a830e6e64623b9f13e12b6cb5e9f9186180c5e26f7f1d9b3871825",
          "sha1": "49ceb352827bf37184d24995f067f05e313f687e",
          "md5": "fde5077cbf34466dccb5e417676c0e4f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "localization-core-0.1.0-javadoc.jar",
          "url": "localization-core-0.1.0-javadoc.jar",
          "size": 191296,
          "sha512": "b3c64cab13d858f6ae7e60c8d53fab9e26a629a3977967cd30a63bb2a8196e9ebbda7a00b5c730011f01d6a403e8f41c3d1277b3bb6fbb5540988f819d3c6ab2",
          "sha256": "be475ca138f3c07d4442fdd20880ac1302eae21a4eb6d13670d65c5b82b7e9df",
          "sha1": "38c25e13184e0065207102358709082e8e936934",
          "md5": "0de63613389183ad7e4b6dc9abf135a2"
        }
      ]
    }
  ]
}
