{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.juloass.tofuxia-engine",
    "module": "render-api",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "engine-core",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "render-api-0.3.1.jar",
          "url": "render-api-0.3.1.jar",
          "size": 10952,
          "sha512": "6f39f87c98eb0f9a9e558f38396d3a72878f1174886ce685fd5534d8f697160429e32d620e1eb27c574ecaeffe0d4b5ef0f12727c5cdd8cbc6137fadd37f8914",
          "sha256": "a0a938da00447d8f263b5624855e0e1ab3b310370ddc4416d38815e90f5aa83f",
          "sha1": "cab544eeb6afb010087dc4657c4e1825e3c42bb6",
          "md5": "ecb6624690302b6c4e32f82c0191ed8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "engine-core",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "render-api-0.3.1.jar",
          "url": "render-api-0.3.1.jar",
          "size": 10952,
          "sha512": "6f39f87c98eb0f9a9e558f38396d3a72878f1174886ce685fd5534d8f697160429e32d620e1eb27c574ecaeffe0d4b5ef0f12727c5cdd8cbc6137fadd37f8914",
          "sha256": "a0a938da00447d8f263b5624855e0e1ab3b310370ddc4416d38815e90f5aa83f",
          "sha1": "cab544eeb6afb010087dc4657c4e1825e3c42bb6",
          "md5": "ecb6624690302b6c4e32f82c0191ed8f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "render-api-0.3.1-sources.jar",
          "url": "render-api-0.3.1-sources.jar",
          "size": 4718,
          "sha512": "aabcea10bf36b579326b74c605c397330cb37290a05c99057bd6b64349e535f602991a599b9c6ae0594f7e3fe3323e5ca3d7db9fbc47d7da19994c525728f60f",
          "sha256": "062245809063caf3c89004037a3be0343b452761e19b72e0345871728a9793db",
          "sha1": "1cf188d4ff8f874e0fe29f047531a49c1f9a037c",
          "md5": "c0da0aa5b19602b34d5117d25b01fcdf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "render-api-0.3.1-javadoc.jar",
          "url": "render-api-0.3.1-javadoc.jar",
          "size": 114794,
          "sha512": "fab49ea589b414eea4a3d943512fe3247c67e39e754db8187a74b9809faa6761b7004dff5559ca1e03d4b747481d4459419cca43d3a33a02802d0a986ad18366",
          "sha256": "557d7aaec113fa76fca624d48b6ae38f4ed2d02af332cfc7e8d77e8274ed929f",
          "sha1": "8bc961e8ea3018bbf1cbd890a6e53524bc19a02b",
          "md5": "d5de1179b23531a75cdfc34785471849"
        }
      ]
    }
  ]
}
