{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.juloass.tofuxia-engine",
    "module": "engine-ui",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "engine-core",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "localization-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "math",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "ui-animation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "engine-ui-0.3.0.jar",
          "url": "engine-ui-0.3.0.jar",
          "size": 101387,
          "sha512": "b96f35f176197e6296d69794a76295ce25c4bfd05b8c2041e222ecf046a33e1928e0feb65fe1ef52cb785d79e845e2c231f783b49ef302175be72955ae26c524",
          "sha256": "d8157e0bfb84771a1a5ecd262fde7cbcdf3fcdc789064e79af8750921fc3d495",
          "sha1": "ba3a46d5fc7ac98078f6de463dd2652846669eaf",
          "md5": "95f1c074716d9a7b73dfd19984732b06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "engine-core",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "localization-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "math",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "ui-animation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "engine-ui-0.3.0.jar",
          "url": "engine-ui-0.3.0.jar",
          "size": 101387,
          "sha512": "b96f35f176197e6296d69794a76295ce25c4bfd05b8c2041e222ecf046a33e1928e0feb65fe1ef52cb785d79e845e2c231f783b49ef302175be72955ae26c524",
          "sha256": "d8157e0bfb84771a1a5ecd262fde7cbcdf3fcdc789064e79af8750921fc3d495",
          "sha1": "ba3a46d5fc7ac98078f6de463dd2652846669eaf",
          "md5": "95f1c074716d9a7b73dfd19984732b06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "engine-ui-0.3.0-sources.jar",
          "url": "engine-ui-0.3.0-sources.jar",
          "size": 40590,
          "sha512": "3cbd56b180ccf78b18d6cc5febc9723f80a2bf4577bd2be8b47b23a36c844131b8b69a79be51acaedc389077510652d0832ef96e160cc792c03a697f5be2d524",
          "sha256": "72e9672fa846249559198f3c56bc3c80f56ee9d6fdff2f36391ca08dcb9a866f",
          "sha1": "4973964093ee81279d795c0097d718bb1e62e1b5",
          "md5": "2167f001ad2fcae30b27a07b0c098d72"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "engine-ui-0.3.0-javadoc.jar",
          "url": "engine-ui-0.3.0-javadoc.jar",
          "size": 277488,
          "sha512": "506fa284841540f26d6f08590de04e72bd0d0f14f88992762e8a65d5f58cb81291f41b017f4fbbe2c1278ffead330eda52392e9af8fcbc6c4e7dcf385462fbf4",
          "sha256": "40d1e45b2086a3b6c546e78c4d17c69926760b0d5c5370bfa3b1f2a2258d4abf",
          "sha1": "8163f6a4f2dfb8810a6dfc1acdb37643571b0883",
          "md5": "7f06506bfe659f5251ba1639ef44ec22"
        }
      ]
    }
  ]
}
