{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.juloass.tofuxia-engine",
    "module": "engine-app",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "engine-default-assets",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "engine-core",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "engine-ui",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "localization-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "audio-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "input-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "squall-core",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "vulkan-renderer",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "engine-app-0.3.0.jar",
          "url": "engine-app-0.3.0.jar",
          "size": 224918,
          "sha512": "94894f1a803c77afcd7d5bd3d6b70d524744155eaa20b50dbc612b38969ec9d3da1be1d775a254421f8da8dd5a00342ecaef005ea6a4fc9686268744767ddff4",
          "sha256": "1ec45b2d0e7c5dc9ff31d6caa6ead55a4ac38b4a4aa737d109b141fba75b50e2",
          "sha1": "ed659bb8e6ac8ec6c24aac54818105258c42df6d",
          "md5": "81e1dd0c0a63f39573502469ef1d9b8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.9"
          }
        },
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "engine-default-assets",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "engine-core",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "engine-ui",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "localization-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "audio-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "input-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.juloass",
          "module": "squall-core",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "io.github.juloass.tofuxia-engine",
          "module": "vulkan-renderer",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "engine-app-0.3.0.jar",
          "url": "engine-app-0.3.0.jar",
          "size": 224918,
          "sha512": "94894f1a803c77afcd7d5bd3d6b70d524744155eaa20b50dbc612b38969ec9d3da1be1d775a254421f8da8dd5a00342ecaef005ea6a4fc9686268744767ddff4",
          "sha256": "1ec45b2d0e7c5dc9ff31d6caa6ead55a4ac38b4a4aa737d109b141fba75b50e2",
          "sha1": "ed659bb8e6ac8ec6c24aac54818105258c42df6d",
          "md5": "81e1dd0c0a63f39573502469ef1d9b8b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "engine-app-0.3.0-sources.jar",
          "url": "engine-app-0.3.0-sources.jar",
          "size": 58772,
          "sha512": "3eb3ffd5c588c782ea3080485c7a2d34da4e098852110fd0b1b7e1140e5bfdf66e56ee575ac375c77269ff169f775eca86e0c40a86014ef8f71c450994c0700e",
          "sha256": "230aea4a656ccb61e953d88d9f05038e1eba72c27fc0f48d63fefa83de867364",
          "sha1": "ee7c0c66475ff70bee0c1393a8483f0a8bc8216b",
          "md5": "3bcc0cf4826b816cbf25bd23fed99a0f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "engine-app-0.3.0-javadoc.jar",
          "url": "engine-app-0.3.0-javadoc.jar",
          "size": 540797,
          "sha512": "82a26583931311b10706590cc2b9ad08fb48058904b6106b1061671cf8cb3bd56e19280ad00992cb155acdd366417f810305573f073612782c3d43e8e0dd1ce3",
          "sha256": "a339a1637c84ea0fe00521cee524b96f116630251be4949719d9b113520bde66",
          "sha1": "d303bb3ed06959593fb2bac9ab14d2cc2b50eb75",
          "md5": "bb03d44436be2660fe4f5df1899d81df"
        }
      ]
    }
  ]
}
